name: Hello World!

on:
    push:
        branches: 
            - master
 
jobs:
    hello_job:
        runs-on: ubuntu-18.04
        steps:
            - name: Say Hello
              run: |
                  "Hello World!"
    
