name: Scheduled Health Check

on:
  schedule:
    - cron: "* * * * *"

jobs:
  healthcheck:
    runs-on: "ubuntu-18.04"
    steps:
      - name: health check
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: "http://pokedex-fullstackopen.herokuapp.com/healthcheck"
          retry-delay: 5s

